"""
Strategy Knowledge Base
Comprehensive information about every chunking, retrieval, and reranking strategy
available in ChunkScope. Powers the info (i) buttons on pipeline nodes.
"""
from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class StrategyInfo:
    id: str
    name: str
    category: str  # "chunking", "retrieval", "reranking"
    summary: str  # 1 sentence
    when_to_use: list[str]
    when_not_to_use: list[str]
    best_for: list[str]  # document types / use cases
    complexity: str  # "simple", "moderate", "advanced"
    latency: str  # "fast", "moderate", "slow"
    cost: str  # "free", "low", "moderate", "high"
    requires_llm: bool
    requires_gpu: bool
    accuracy_tier: str  # "baseline", "good", "excellent", "state-of-art"
    pairs_well_with: list[str]  # IDs of complementary strategies
    example_config: dict
    decision_factors: list[str]
    tradeoffs: str  # 1-2 sentence tradeoff summary
    pro_tip: str


# ---------------------------------------------------------------------------
# Chunking Strategies
# ---------------------------------------------------------------------------

_CHUNKING_STRATEGIES: list[StrategyInfo] = [
    StrategyInfo(
        id="fixed",
        name="Fixed-Size Chunking",
        category="chunking",
        summary="Splits text into equal-sized chunks by character or token count.",
        when_to_use=[
            "Text is homogeneous and uniform in structure",
            "You need predictable, consistent chunk sizes",
            "Processing speed is a priority over semantic coherence",
            "Working with plain-text logs or transcripts",
        ],
        when_not_to_use=[
            "Documents have clear structural boundaries (headings, paragraphs)",
            "Semantic coherence within chunks matters",
            "Documents mix code, tables, and prose",
        ],
        best_for=["plain text", "logs", "transcripts", "homogeneous corpora"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="baseline",
        pairs_well_with=["hybrid", "cross_encoder", "bm25_rerank"],
        example_config={"chunk_size": 512, "chunk_overlap": 50},
        decision_factors=[
            "Is the text uniform without clear section boundaries?",
            "Do you need the fastest possible chunking?",
            "Is chunk-size predictability important for downstream models?",
        ],
        tradeoffs="Fastest and simplest, but often splits sentences and ideas mid-thought, hurting retrieval relevance.",
        pro_tip="Use a small overlap (10-15%) to avoid cutting important sentences at boundaries.",
    ),
    StrategyInfo(
        id="recursive",
        name="Recursive Character Splitting",
        category="chunking",
        summary="Recursively splits text using a hierarchy of separators (paragraphs, sentences, words) to stay within size limits.",
        when_to_use=[
            "You need a solid general-purpose default",
            "Documents are a mix of paragraphs and prose",
            "You want a good balance between speed and quality",
            "You are unsure which chunking method to pick",
        ],
        when_not_to_use=[
            "Documents are heavily structured with headings and tables",
            "You need topic-boundary-aware splits",
            "Working exclusively with source code",
        ],
        best_for=["general documents", "articles", "reports", "mixed content"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "corrective", "cascade"],
        example_config={"chunk_size": 512, "chunk_overlap": 50, "separators": ["\n\n", "\n", ". ", " "]},
        decision_factors=[
            "Is this your first pipeline and you want a safe default?",
            "Does the document lack clear structural markers?",
            "Do you want fast chunking without an LLM?",
        ],
        tradeoffs="Best general-purpose choice with near-zero cost, but does not understand topic boundaries or document structure.",
        pro_tip="Start here and only switch to semantic or heading-based if retrieval quality is noticeably poor.",
    ),
    StrategyInfo(
        id="semantic",
        name="Semantic Chunking",
        category="chunking",
        summary="Uses embedding similarity between sentences to detect topic boundaries and split at natural breakpoints.",
        when_to_use=[
            "Topics shift within a single document",
            "Retrieval quality is more important than speed",
            "Documents are long-form with multiple subjects",
            "You want chunks that represent coherent ideas",
        ],
        when_not_to_use=[
            "Documents are short or single-topic",
            "Processing speed is critical",
            "You do not have access to an embedding model",
            "Budget is very constrained (requires embedding calls)",
        ],
        best_for=["long articles", "textbooks", "research papers", "multi-topic documents"],
        complexity="moderate",
        latency="moderate",
        cost="low",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "cross_encoder", "lost_in_middle"],
        example_config={"breakpoint_threshold": 0.5, "embedding_model": "text-embedding-3-small"},
        decision_factors=[
            "Do topics change frequently within your documents?",
            "Can you afford the extra latency of embedding each sentence?",
            "Is retrieval precision critical for your use case?",
        ],
        tradeoffs="Produces the most coherent chunks by detecting topic shifts, but requires embedding computation for every sentence, adding latency and cost.",
        pro_tip="Tune the breakpoint_threshold: lower values create more chunks (higher precision), higher values create fewer chunks (more context per chunk).",
    ),
    StrategyInfo(
        id="sentence_window",
        name="Sentence Window Chunking",
        category="chunking",
        summary="Creates chunks centered around individual sentences with surrounding context windows.",
        when_to_use=[
            "Building a Q&A system where precise sentence retrieval matters",
            "You want fine-grained retrieval with broader context",
            "Documents contain dense factual information",
        ],
        when_not_to_use=[
            "Documents are short or conversational",
            "You need large context chunks",
            "Processing long documents where sentence segmentation is expensive",
        ],
        best_for=["Q&A systems", "fact-dense documents", "encyclopedias", "knowledge bases"],
        complexity="moderate",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["sentence_window_retrieval", "cross_encoder", "lost_in_middle"],
        example_config={"window_size": 3, "overlap": 1},
        decision_factors=[
            "Is sentence-level precision important?",
            "Do users ask factoid questions?",
            "Is the document dense with distinct facts per sentence?",
        ],
        tradeoffs="Excellent sentence-level precision for factoid queries, but creates many small chunks that may lack broader context for complex questions.",
        pro_tip="Pair with the sentence_window retriever to get the best of both worlds: search on small chunks, return with expanded context.",
    ),
    StrategyInfo(
        id="paragraph",
        name="Paragraph Chunking",
        category="chunking",
        summary="Splits text at paragraph boundaries, respecting the author's intended structure.",
        when_to_use=[
            "Documents have well-defined paragraphs",
            "You want to preserve the author's logical groupings",
            "Working with edited, published content",
        ],
        when_not_to_use=[
            "Text has no paragraph breaks (e.g., OCR output)",
            "Paragraphs are very long (>2000 chars)",
            "Documents are list-heavy or table-heavy",
        ],
        best_for=["articles", "blog posts", "well-formatted reports", "books"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "cross_encoder", "diversity"],
        example_config={"min_chunk_size": 100, "max_chunk_size": 1500},
        decision_factors=[
            "Are the documents well-formatted with clear paragraph breaks?",
            "Do paragraphs represent self-contained ideas?",
            "Are paragraph sizes reasonably consistent?",
        ],
        tradeoffs="Preserves natural document structure with zero computational overhead, but chunk sizes can be highly variable depending on the document.",
        pro_tip="Add a max_chunk_size guard to split overly long paragraphs, and merge very short ones.",
    ),
    StrategyInfo(
        id="code_aware",
        name="Code-Aware Chunking",
        category="chunking",
        summary="Understands code structure and preserves functions, classes, and code blocks as complete units.",
        when_to_use=[
            "Documents contain source code or code examples",
            "Working with technical documentation or READMEs",
            "Code block integrity is essential for retrieval quality",
        ],
        when_not_to_use=[
            "Documents contain no code",
            "Working with pure natural language text",
        ],
        best_for=["source code", "technical docs", "API references", "tutorials with code"],
        complexity="moderate",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "bge", "cross_encoder"],
        example_config={"language": "python", "max_chunk_size": 1500},
        decision_factors=[
            "Does the corpus contain code blocks?",
            "Would splitting a function across chunks hurt retrieval?",
            "Are users searching for code-related answers?",
        ],
        tradeoffs="Essential for codebases and technical docs, but adds no value for pure prose and can produce uneven chunk sizes.",
        pro_tip="Combine with heading_based for docs that mix code and narrative (e.g., Jupyter notebooks exported to markdown).",
    ),
    StrategyInfo(
        id="heading_based",
        name="Heading-Based Chunking",
        category="chunking",
        summary="Splits at markdown or HTML headings, using document structure as natural boundaries.",
        when_to_use=[
            "Documents have clear heading hierarchy (H1, H2, H3)",
            "Working with markdown, HTML, or structured docs",
            "Sections are self-contained topics",
        ],
        when_not_to_use=[
            "Documents lack headings",
            "Headings are inconsistent or decorative",
            "Working with plain text or OCR output",
        ],
        best_for=["markdown docs", "wikis", "knowledge base articles", "structured reports"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "cross_encoder", "metadata_filter"],
        example_config={"heading_levels": [1, 2, 3], "max_chunk_size": 2000},
        decision_factors=[
            "Does the document have a clear heading structure?",
            "Are headings descriptive of section content?",
            "Do sections represent distinct topics?",
        ],
        tradeoffs="Leverages the author's outline for near-perfect topical splits, but completely depends on consistent heading usage in the source documents.",
        pro_tip="Include heading text as metadata on each chunk -- it dramatically improves retrieval when users reference section names.",
    ),
    StrategyInfo(
        id="contextual",
        name="Contextual Chunking",
        category="chunking",
        summary="Anthropic's approach: uses an LLM to generate a contextual preamble for each chunk, enriching it with document-level context.",
        when_to_use=[
            "Maximum retrieval accuracy is the goal",
            "Budget allows LLM calls per chunk",
            "Documents lose meaning when read in isolation",
            "Building a high-stakes production RAG system",
        ],
        when_not_to_use=[
            "Budget is limited (LLM cost per chunk adds up)",
            "Processing speed matters more than accuracy",
            "Corpus is very large (costs scale linearly with chunks)",
        ],
        best_for=["legal documents", "medical records", "financial reports", "high-stakes Q&A"],
        complexity="advanced",
        latency="slow",
        cost="high",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="state-of-art",
        pairs_well_with=["dense", "lost_in_middle", "cross_encoder"],
        example_config={"base_chunker": "recursive", "llm_model": "claude-3-haiku-20240307"},
        decision_factors=[
            "Is the accuracy improvement worth the LLM cost?",
            "How large is the corpus? (cost = chunks x LLM price)",
            "Do chunks need document-level context to make sense?",
        ],
        tradeoffs="Produces the highest-quality chunks with full document context, but every chunk requires an LLM call, making it the most expensive strategy by far.",
        pro_tip="Use a cheap, fast model (like Haiku) for the preamble generation. The context only needs to be a sentence or two.",
    ),
]

# ---------------------------------------------------------------------------
# Retrieval Strategies
# ---------------------------------------------------------------------------

_RETRIEVAL_STRATEGIES: list[StrategyInfo] = [
    StrategyInfo(
        id="dense",
        name="Dense Vector Search",
        category="retrieval",
        summary="Standard cosine/dot-product similarity search over embedding vectors.",
        when_to_use=[
            "You want a simple, fast baseline",
            "Queries are natural language and semantically clear",
            "You have a good embedding model",
        ],
        when_not_to_use=[
            "Users search with exact keywords, acronyms, or IDs",
            "Documents contain many domain-specific terms",
            "You need the highest possible recall",
        ],
        best_for=["general Q&A", "semantic search", "natural language queries"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="baseline",
        pairs_well_with=["semantic", "cross_encoder", "lost_in_middle"],
        example_config={"top_k": 10, "similarity_threshold": 0.7},
        decision_factors=[
            "Is this a first-pass baseline?",
            "Are queries semantic rather than keyword-based?",
            "Is latency the top priority?",
        ],
        tradeoffs="Fast and simple, but misses exact keyword matches and struggles with domain-specific jargon that embeddings have not seen.",
        pro_tip="If dense retrieval alone is underperforming, switch to hybrid before tuning anything else -- it is almost always a bigger win.",
    ),
    StrategyInfo(
        id="hybrid",
        name="Hybrid Search (Dense + BM25)",
        category="retrieval",
        summary="Combines dense vector search with BM25 keyword matching for the best of both worlds.",
        when_to_use=[
            "You want the production-standard default",
            "Documents contain both natural language and specific terms",
            "You need to catch both semantic and keyword matches",
        ],
        when_not_to_use=[
            "Your corpus is tiny (<50 chunks) and latency matters",
            "You only care about semantic similarity",
        ],
        best_for=["production RAG", "technical documentation", "enterprise search", "any corpus"],
        complexity="moderate",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["recursive", "semantic", "cross_encoder", "cascade"],
        example_config={"top_k": 10, "alpha": 0.5, "bm25_weight": 0.5, "dense_weight": 0.5},
        decision_factors=[
            "Is this a production system?",
            "Do users use both natural language and exact terms?",
            "Do you want a single retriever that covers most bases?",
        ],
        tradeoffs="Gold-standard balance of semantic understanding and keyword precision with minimal latency overhead. Slightly more complex to configure (alpha weighting).",
        pro_tip="Start with alpha=0.5 (equal weighting), then tune: increase BM25 weight for technical/jargon-heavy corpora, increase dense weight for conversational queries.",
    ),
    StrategyInfo(
        id="multi_query",
        name="Multi-Query Retrieval",
        category="retrieval",
        summary="Uses an LLM to generate multiple reformulations of the query, then retrieves and merges results.",
        when_to_use=[
            "Queries are often ambiguous or under-specified",
            "Users phrase the same intent in very different ways",
            "Recall is more important than latency",
        ],
        when_not_to_use=[
            "Queries are clear and specific",
            "Latency is critical (adds an LLM call)",
            "Budget is very constrained",
        ],
        best_for=["ambiguous queries", "exploratory search", "user-facing search"],
        complexity="moderate",
        latency="moderate",
        cost="low",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["recursive", "cross_encoder", "diversity"],
        example_config={"num_queries": 3, "llm_model": "gpt-4o-mini"},
        decision_factors=[
            "Are user queries frequently ambiguous?",
            "Can you tolerate an extra LLM call per query?",
            "Is recall more important than speed?",
        ],
        tradeoffs="Significantly improves recall on ambiguous queries by covering more query interpretations, but adds LLM latency and cost for every search.",
        pro_tip="Use a fast, cheap model (GPT-4o-mini or Haiku) for query generation. 3 variants is the sweet spot -- more rarely helps.",
    ),
    StrategyInfo(
        id="hyde",
        name="HyDE (Hypothetical Document Embeddings)",
        category="retrieval",
        summary="Generates a hypothetical answer to the query using an LLM, then searches for real documents similar to that answer.",
        when_to_use=[
            "Queries are factoid questions with expected specific answers",
            "There is a vocabulary mismatch between queries and documents",
            "You want to bridge the query-document semantic gap",
        ],
        when_not_to_use=[
            "Queries are exploratory or open-ended",
            "The LLM might hallucinate answers in your domain",
            "Latency is critical",
        ],
        best_for=["factoid Q&A", "technical support", "FAQ matching"],
        complexity="moderate",
        latency="moderate",
        cost="low",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["recursive", "cross_encoder", "cascade"],
        example_config={"llm_model": "gpt-4o-mini", "num_hypothetical": 1},
        decision_factors=[
            "Are queries phrased as questions with specific expected answers?",
            "Is there a vocabulary gap between how users ask and how docs are written?",
            "Is the domain well-known enough that the LLM won't hallucinate?",
        ],
        tradeoffs="Clever bridge between query and document space that works well for factoid questions, but the hypothetical answer can mislead search if the LLM hallucinates.",
        pro_tip="Works best when the LLM has domain knowledge. For niche domains, consider multi_query instead.",
    ),
    StrategyInfo(
        id="parent_document",
        name="Parent-Child Document Retrieval",
        category="retrieval",
        summary="Searches over small child chunks for precision, then returns the larger parent chunk for context.",
        when_to_use=[
            "You want both search precision and answer context",
            "Documents are long and the LLM needs surrounding context",
            "Small chunks match well but lack enough context for generation",
        ],
        when_not_to_use=[
            "Documents are already short",
            "Storage is very constrained (stores 2x chunks)",
            "You need the simplest possible pipeline",
        ],
        best_for=["long documents", "legal contracts", "technical manuals", "research papers"],
        complexity="moderate",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["recursive", "cross_encoder", "lost_in_middle"],
        example_config={"child_chunk_size": 200, "parent_chunk_size": 1000, "top_k": 5},
        decision_factors=[
            "Are your documents long enough to benefit from two chunk sizes?",
            "Does the LLM need more context than what a small chunk provides?",
            "Can you afford the extra storage for parent chunks?",
        ],
        tradeoffs="Best of both worlds -- precise retrieval on small chunks, rich context from parents -- but doubles storage requirements and adds indexing complexity.",
        pro_tip="Set child chunks to ~200 tokens and parents to ~1000 tokens. The child should be small enough to match precisely, the parent large enough to answer fully.",
    ),
    StrategyInfo(
        id="mmr",
        name="Maximal Marginal Relevance (MMR)",
        category="retrieval",
        summary="Balances relevance with diversity to reduce redundancy in retrieved results.",
        when_to_use=[
            "Retrieved results are too similar to each other",
            "You want diverse perspectives on a topic",
            "The top-k results often repeat the same information",
        ],
        when_not_to_use=[
            "You want the absolute most relevant results regardless of overlap",
            "The corpus has little redundancy",
        ],
        best_for=["diverse answer generation", "summarization", "exploratory queries"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["recursive", "semantic", "cross_encoder"],
        example_config={"top_k": 10, "lambda_mult": 0.7, "fetch_k": 20},
        decision_factors=[
            "Are your top results repetitive?",
            "Does the answer need multiple perspectives?",
            "Is the corpus redundant (e.g., many similar articles)?",
        ],
        tradeoffs="Effectively reduces redundancy in results, but may push the single most relevant chunk to a lower rank in favor of diversity.",
        pro_tip="Set lambda_mult between 0.5 (max diversity) and 1.0 (max relevance). Start at 0.7 and adjust based on result quality.",
    ),
    StrategyInfo(
        id="query_expansion",
        name="Query Expansion",
        category="retrieval",
        summary="Adds synonyms, related terms, and expanded phrasing to the query before searching.",
        when_to_use=[
            "Users use different terminology than the documents",
            "You want a simple recall boost without an LLM",
            "Domain has many synonyms or abbreviations",
        ],
        when_not_to_use=[
            "Queries are already well-matched to document vocabulary",
            "Expansion might add noise (very broad queries)",
        ],
        best_for=["enterprise search", "medical terminology", "technical jargon"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "cross_encoder", "bm25_rerank"],
        example_config={"expansion_method": "wordnet", "max_expansions": 3},
        decision_factors=[
            "Is there a vocabulary gap between queries and documents?",
            "Do you want a cheap alternative to multi_query?",
            "Does the domain have established synonym lists?",
        ],
        tradeoffs="Simple, free recall boost by covering more vocabulary, but can introduce noise if expansions are not domain-relevant.",
        pro_tip="For domain-specific corpora, build a custom synonym map rather than relying on generic WordNet expansions.",
    ),
    StrategyInfo(
        id="sentence_window_retrieval",
        name="Sentence Window Retrieval",
        category="retrieval",
        summary="Retrieves individual sentences with high precision, then expands to include surrounding context window.",
        when_to_use=[
            "You need sentence-level precision for factoid questions",
            "Each sentence in the corpus carries distinct information",
            "Paired with sentence_window chunking",
        ],
        when_not_to_use=[
            "Queries need paragraph-level or section-level context",
            "Chunks are already large enough",
            "Not using sentence-level chunking",
        ],
        best_for=["factoid Q&A", "knowledge bases", "dense reference material"],
        complexity="moderate",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["sentence_window", "cross_encoder", "lost_in_middle"],
        example_config={"window_size": 3, "top_k": 5},
        decision_factors=[
            "Are you using sentence_window chunking?",
            "Do users ask precise factoid questions?",
            "Is sentence-level matching important?",
        ],
        tradeoffs="Excellent precision for factoid retrieval with context expansion, but requires sentence-level chunking and may miss broader thematic matches.",
        pro_tip="Always pair with sentence_window chunking. The retriever expects sentence-level chunks with stored neighboring context.",
    ),
    StrategyInfo(
        id="contextual_compression",
        name="Contextual Compression",
        category="retrieval",
        summary="Uses an LLM to extract only the relevant portions from retrieved chunks, reducing noise sent to the generator.",
        when_to_use=[
            "Retrieved chunks contain a lot of irrelevant content",
            "You want to maximize signal-to-noise in the context window",
            "The LLM context window is limited",
        ],
        when_not_to_use=[
            "Chunks are already concise and relevant",
            "Latency is critical (adds LLM call per chunk)",
            "Budget is tight",
        ],
        best_for=["long documents", "noisy corpora", "limited context windows"],
        complexity="advanced",
        latency="slow",
        cost="moderate",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["recursive", "paragraph", "cross_encoder"],
        example_config={"llm_model": "gpt-4o-mini", "max_compressed_length": 200},
        decision_factors=[
            "Are chunks noisy with lots of irrelevant content?",
            "Is the LLM context window a bottleneck?",
            "Can you afford an LLM call per retrieved chunk?",
        ],
        tradeoffs="Dramatically reduces noise in the final context, but adds an LLM call per chunk, significantly increasing latency and cost.",
        pro_tip="Apply after reranking on only the top 3-5 chunks to keep costs manageable. Do not compress all candidates.",
    ),
    StrategyInfo(
        id="self_query",
        name="Self-Query Retrieval",
        category="retrieval",
        summary="Uses an LLM to parse the user query into a semantic search plus structured metadata filters.",
        when_to_use=[
            "Documents have rich metadata (date, author, type, category)",
            "Users naturally include filter criteria in queries",
            "You want automatic metadata-aware search",
        ],
        when_not_to_use=[
            "Documents lack structured metadata",
            "Queries are purely semantic without filter intent",
            "Budget does not allow an LLM call per query",
        ],
        best_for=["enterprise document search", "e-commerce", "catalog search", "structured knowledge bases"],
        complexity="advanced",
        latency="moderate",
        cost="low",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["heading_based", "cross_encoder", "contextual_rerank"],
        example_config={"llm_model": "gpt-4o-mini", "metadata_fields": ["doc_type", "date", "author"]},
        decision_factors=[
            "Do documents have structured metadata fields?",
            "Do users ask questions like 'show me reports from Q4 2024'?",
            "Can you tolerate an LLM call per query for filter extraction?",
        ],
        tradeoffs="Intelligently combines semantic search with metadata filtering, but requires an LLM call per query and well-defined metadata schema.",
        pro_tip="Define your metadata schema clearly upfront. The LLM needs to know exactly which fields and value types are available.",
    ),
    StrategyInfo(
        id="metadata_filter",
        name="Metadata Filter Retrieval",
        category="retrieval",
        summary="Pre-filters documents by metadata (type, date, source) before running semantic search.",
        when_to_use=[
            "Corpus is large and heterogeneous",
            "Documents have reliable metadata tags",
            "You need to scope search to specific document subsets",
        ],
        when_not_to_use=[
            "Documents lack metadata",
            "All documents are the same type",
            "You want fully automated filter detection (use self_query instead)",
        ],
        best_for=["large corpora", "multi-source knowledge bases", "enterprise search"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "cross_encoder", "cascade"],
        example_config={"filter_fields": ["doc_type", "source", "date_range"], "top_k": 10},
        decision_factors=[
            "Do documents have metadata you can filter on?",
            "Do users specify filters explicitly (e.g., dropdown selections)?",
            "Is the corpus too large for unfiltered search?",
        ],
        tradeoffs="Simple and fast way to scope search, but filters must be provided explicitly by the application or user.",
        pro_tip="Combine with self_query for automatic filter extraction from natural language, or use UI dropdowns for explicit filtering.",
    ),
    StrategyInfo(
        id="time_weighted",
        name="Time-Weighted Retrieval",
        category="retrieval",
        summary="Boosts recent documents in search results, combining semantic relevance with temporal recency.",
        when_to_use=[
            "Knowledge base is constantly updated",
            "Recent information should take priority",
            "Working with news, changelogs, or evolving documentation",
        ],
        when_not_to_use=[
            "All documents are equally relevant regardless of age",
            "The corpus is static and rarely updated",
            "Historical accuracy matters more than recency",
        ],
        best_for=["news", "changelogs", "evolving docs", "customer support with versioned products"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "cross_encoder", "metadata_filter"],
        example_config={"decay_rate": 0.01, "time_field": "updated_at", "top_k": 10},
        decision_factors=[
            "Does document freshness matter for your use case?",
            "Is the corpus regularly updated?",
            "Should newer information override older information?",
        ],
        tradeoffs="Essential for evolving knowledge bases where freshness matters, but can suppress highly relevant older documents.",
        pro_tip="Tune the decay_rate carefully. Too aggressive and you lose valuable older content; too gentle and the time weighting has no effect.",
    ),
    StrategyInfo(
        id="ensemble",
        name="Ensemble Retrieval",
        category="retrieval",
        summary="Runs multiple retrieval strategies in parallel and merges results using reciprocal rank fusion.",
        when_to_use=[
            "Maximum recall is the goal",
            "Different retrievers excel at different query types",
            "You can afford higher latency for better coverage",
        ],
        when_not_to_use=[
            "Latency is critical",
            "A single retriever already performs well",
            "Simplicity is preferred",
        ],
        best_for=["high-stakes search", "diverse query patterns", "maximum recall scenarios"],
        complexity="advanced",
        latency="moderate",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["recursive", "cascade", "cross_encoder"],
        example_config={"retrievers": ["dense", "hybrid", "mmr"], "weights": [0.4, 0.4, 0.2]},
        decision_factors=[
            "Do you need the highest possible recall?",
            "Do different query types benefit from different retrievers?",
            "Can you afford running multiple retrievers per query?",
        ],
        tradeoffs="Maximum recall by combining multiple retriever perspectives, but multiplies latency and complexity.",
        pro_tip="Use 2-3 complementary retrievers (e.g., dense + BM25 + MMR). More than 3 rarely improves results but always increases latency.",
    ),
    StrategyInfo(
        id="sub_query",
        name="Sub-Query Decomposition",
        category="retrieval",
        summary="Breaks complex multi-part queries into simpler sub-questions, retrieves for each, and merges results.",
        when_to_use=[
            "Users ask complex, multi-faceted questions",
            "A single query cannot capture all aspects of the information need",
            "Queries often contain 'and', 'also', or 'compare'",
        ],
        when_not_to_use=[
            "Queries are simple and single-focus",
            "Latency is critical (multiple retrieval rounds)",
            "Budget is constrained",
        ],
        best_for=["analytical questions", "comparative queries", "multi-hop reasoning"],
        complexity="advanced",
        latency="slow",
        cost="low",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["recursive", "cross_encoder", "lost_in_middle"],
        example_config={"llm_model": "gpt-4o-mini", "max_sub_queries": 4},
        decision_factors=[
            "Are user queries complex with multiple parts?",
            "Do answers require information from multiple document sections?",
            "Can you tolerate the latency of multiple retrieval rounds?",
        ],
        tradeoffs="Handles complex multi-part questions that stump single-query retrieval, but adds significant latency from LLM decomposition plus multiple search rounds.",
        pro_tip="Cap sub-queries at 3-4. Beyond that, results overlap heavily and latency grows linearly.",
    ),
    StrategyInfo(
        id="step_back",
        name="Step-Back Prompting Retrieval",
        category="retrieval",
        summary="Generates a more abstract, broader version of the query to retrieve foundational context before answering specifics.",
        when_to_use=[
            "Users ask very specific technical questions",
            "The answer requires understanding broader context first",
            "Specific queries fail because they are too narrow",
        ],
        when_not_to_use=[
            "Queries are already at the right abstraction level",
            "Documents are narrowly focused on specific topics",
            "Latency is critical",
        ],
        best_for=["technical Q&A", "troubleshooting", "academic research", "how-it-works questions"],
        complexity="moderate",
        latency="moderate",
        cost="low",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["recursive", "cross_encoder", "cascade"],
        example_config={"llm_model": "gpt-4o-mini"},
        decision_factors=[
            "Do specific queries often return no results?",
            "Would broader context improve the answer?",
            "Are users asking about specific instances of general concepts?",
        ],
        tradeoffs="Excellent for specific technical questions that need foundational context, but the abstracted query may retrieve overly general content.",
        pro_tip="Combine results from both the original specific query and the step-back query, then rerank to get the best of both.",
    ),
    StrategyInfo(
        id="adaptive",
        name="Adaptive Retrieval",
        category="retrieval",
        summary="Automatically classifies query complexity and routes to the best retrieval strategy.",
        when_to_use=[
            "Query patterns are diverse (simple and complex mixed)",
            "You want automatic strategy selection",
            "Building a general-purpose search system",
        ],
        when_not_to_use=[
            "All queries are similar in complexity",
            "You want predictable, consistent retrieval behavior",
            "The classification overhead is not justified",
        ],
        best_for=["general-purpose search", "varied user base", "production systems"],
        complexity="advanced",
        latency="moderate",
        cost="low",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["recursive", "cascade", "cross_encoder"],
        example_config={"strategies": {"simple": "dense", "moderate": "hybrid", "complex": "multi_query"}},
        decision_factors=[
            "Are queries highly variable in complexity?",
            "Do you want the system to auto-optimize per query?",
            "Can you afford a classification step per query?",
        ],
        tradeoffs="Smart routing optimizes per-query performance, but adds classification overhead and complexity in debugging which strategy was chosen.",
        pro_tip="Log which strategy was selected for each query. This data is gold for understanding your query patterns and tuning the router.",
    ),
    StrategyInfo(
        id="corrective",
        name="Corrective RAG (CRAG)",
        category="retrieval",
        summary="Self-correcting retrieval that evaluates result quality and re-retrieves with refined queries if needed.",
        when_to_use=[
            "Retrieval quality is inconsistent",
            "You want the system to self-heal on bad retrievals",
            "Building a high-reliability production system",
        ],
        when_not_to_use=[
            "Latency is critical (adds evaluation + potential re-retrieval)",
            "Budget is very constrained",
            "Simple queries that rarely fail retrieval",
        ],
        best_for=["high-stakes Q&A", "production systems", "customer-facing search"],
        complexity="advanced",
        latency="slow",
        cost="moderate",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="state-of-art",
        pairs_well_with=["recursive", "cascade", "cross_encoder"],
        example_config={"llm_model": "gpt-4o-mini", "relevance_threshold": 0.5, "max_retries": 2},
        decision_factors=[
            "Is retrieval reliability critical?",
            "Can you afford the latency of evaluation + potential re-retrieval?",
            "Is it acceptable for some queries to take 2-3x longer?",
        ],
        tradeoffs="Most robust retrieval with self-correction, but significantly increases latency and cost when corrections are triggered.",
        pro_tip="Monitor the correction rate. If more than 30% of queries trigger re-retrieval, your base retriever or chunking needs improvement.",
    ),
    StrategyInfo(
        id="document_summary",
        name="Document Summary Retrieval",
        category="retrieval",
        summary="Two-stage search: first finds relevant documents via summaries, then retrieves specific chunks from those documents.",
        when_to_use=[
            "Corpus is very large with many distinct documents",
            "You want to narrow search to the right document first",
            "Documents are self-contained units (reports, papers, contracts)",
        ],
        when_not_to_use=[
            "Corpus is small or documents are very similar",
            "All chunks could come from any document",
            "Summary generation cost is prohibitive",
        ],
        best_for=["large document collections", "paper repositories", "contract databases", "report archives"],
        complexity="advanced",
        latency="moderate",
        cost="low",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["heading_based", "cross_encoder", "cascade"],
        example_config={"summary_max_length": 500, "top_docs": 3, "chunks_per_doc": 5},
        decision_factors=[
            "Is the corpus large enough that narrowing to the right document helps?",
            "Are documents self-contained units with distinct topics?",
            "Can you pre-compute document summaries at indexing time?",
        ],
        tradeoffs="Efficiently narrows search in large corpora by finding the right document first, but depends on summary quality and adds a two-stage pipeline.",
        pro_tip="Pre-compute summaries at indexing time, not at query time. This turns the cost into a one-time expense.",
    ),
]

# ---------------------------------------------------------------------------
# Reranking Strategies
# ---------------------------------------------------------------------------

_RERANKING_STRATEGIES: list[StrategyInfo] = [
    StrategyInfo(
        id="cross_encoder",
        name="Cross-Encoder Reranking",
        category="reranking",
        summary="Uses a cross-encoder neural model to score query-document pairs with deep interaction, producing highly accurate relevance scores.",
        when_to_use=[
            "You want the best accuracy-to-speed ratio for reranking",
            "A standard, well-tested reranking solution is needed",
            "Working with English text",
        ],
        when_not_to_use=[
            "You need zero-dependency, ultra-fast reranking",
            "Working with languages the model was not trained on",
        ],
        best_for=["general reranking", "production pipelines", "English text"],
        complexity="moderate",
        latency="moderate",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "recursive", "semantic", "lost_in_middle"],
        example_config={"model_name": "cross-encoder/ms-marco-MiniLM-L-6-v2", "top_n": 5},
        decision_factors=[
            "Is this a production pipeline?",
            "Do you want the standard reranking choice?",
            "Is a small model download acceptable?",
        ],
        tradeoffs="Best accuracy/speed tradeoff for reranking. Requires model download but runs on CPU. Slightly slower than keyword-based rerankers.",
        pro_tip="Use ms-marco-MiniLM-L-6-v2 for speed or ms-marco-MiniLM-L-12-v2 for slightly better accuracy. The L-6 model is usually sufficient.",
    ),
    StrategyInfo(
        id="cohere",
        name="Cohere Rerank",
        category="reranking",
        summary="Cloud-based reranking API by Cohere, offering high-quality relevance scoring with zero local setup.",
        when_to_use=[
            "You want high-quality reranking with no local model management",
            "An API key and per-query cost are acceptable",
            "Working with multilingual content",
        ],
        when_not_to_use=[
            "Budget is tight (per-query API cost)",
            "You need offline or air-gapped operation",
            "Data cannot leave your infrastructure",
        ],
        best_for=["production RAG", "multilingual search", "quick prototyping"],
        complexity="simple",
        latency="moderate",
        cost="low",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "recursive", "lost_in_middle"],
        example_config={"model": "rerank-english-v3.0", "top_n": 5},
        decision_factors=[
            "Is an API cost per query acceptable?",
            "Do you need multilingual support?",
            "Do you want zero local setup?",
        ],
        tradeoffs="Excellent quality with zero infrastructure, but costs money per query and requires internet connectivity.",
        pro_tip="Use rerank-english-v3.0 for English and rerank-multilingual-v3.0 for other languages. Batch rerank calls when possible.",
    ),
    StrategyInfo(
        id="bm25_rerank",
        name="BM25 Reranking",
        category="reranking",
        summary="Keyword-based rescoring using BM25 algorithm, complementing semantic retrieval with exact-match signals.",
        when_to_use=[
            "You want a free, fast keyword-based reranking pass",
            "Retrieved results came from purely semantic search",
            "Documents contain important exact terms or IDs",
        ],
        when_not_to_use=[
            "Results already incorporate BM25 (e.g., from hybrid retrieval)",
            "Query terms are not present in the documents",
        ],
        best_for=["keyword boosting", "technical documents with specific terms", "complementing semantic search"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="baseline",
        pairs_well_with=["dense", "query_expansion", "lost_in_middle"],
        example_config={"k1": 1.5, "b": 0.75, "top_n": 10},
        decision_factors=[
            "Is the initial retrieval purely semantic (no BM25)?",
            "Do documents contain critical exact-match keywords?",
            "Do you want a free, zero-dependency reranker?",
        ],
        tradeoffs="Free and instantaneous keyword-based boost, but adds no value on top of hybrid retrieval and misses semantic matches.",
        pro_tip="Most useful as the first stage in a cascade: fast BM25 filter, then a neural reranker on the top results.",
    ),
    StrategyInfo(
        id="rrf",
        name="Reciprocal Rank Fusion (RRF)",
        category="reranking",
        summary="Merges multiple ranked lists using reciprocal rank scores, commonly used to combine retriever outputs.",
        when_to_use=[
            "You have multiple ranked result lists to merge",
            "Using ensemble retrieval",
            "You want a parameter-free fusion method",
        ],
        when_not_to_use=[
            "You only have a single ranked list",
            "You need a learned scoring model",
        ],
        best_for=["ensemble retrieval", "multi-strategy fusion", "rank aggregation"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["ensemble", "hybrid", "cascade"],
        example_config={"k": 60},
        decision_factors=[
            "Do you need to merge multiple ranked lists?",
            "Is this an internal component of a larger pipeline?",
            "Do you want a simple, proven fusion method?",
        ],
        tradeoffs="Simple, effective, and parameter-free fusion of multiple rankings, but treats all rankers equally unless weighted.",
        pro_tip="The k parameter (default 60) controls how much weight is given to lower-ranked items. Lower k emphasizes top ranks more.",
    ),
    StrategyInfo(
        id="llm_pointwise",
        name="LLM Pointwise Reranking",
        category="reranking",
        summary="Uses an LLM to independently score each document's relevance to the query on a numeric scale.",
        when_to_use=[
            "You need fine-grained relevance scores with explanations",
            "The reranking task requires reasoning (not just pattern matching)",
            "Budget allows LLM calls per candidate document",
        ],
        when_not_to_use=[
            "Latency is critical (LLM call per document)",
            "Budget is constrained",
            "Candidate set is large (>20 documents)",
        ],
        best_for=["high-stakes search", "explainable reranking", "small candidate sets"],
        complexity="advanced",
        latency="slow",
        cost="high",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "recursive", "lost_in_middle"],
        example_config={"llm_model": "gpt-4o-mini", "scale": "1-10", "top_n": 5},
        decision_factors=[
            "Do you need per-document relevance explanations?",
            "Is the candidate set small (<20 documents)?",
            "Can you afford an LLM call per candidate?",
        ],
        tradeoffs="Flexible and explainable scoring with LLM reasoning, but expensive (1 LLM call per document) and slow.",
        pro_tip="Always apply after a fast pre-filter (BM25 or cross-encoder) to limit the candidate set to 5-10 documents.",
    ),
    StrategyInfo(
        id="lost_in_middle",
        name="Lost-in-the-Middle Reordering",
        category="reranking",
        summary="Reorders results so the most relevant documents are at the start and end of the context, where LLMs pay the most attention.",
        when_to_use=[
            "Using an LLM for answer generation",
            "You want a free accuracy boost with zero downside",
            "Results are already ranked by relevance",
        ],
        when_not_to_use=[
            "Not using an LLM for generation",
            "Only returning 1-2 documents",
        ],
        best_for=["any LLM-based RAG pipeline", "long context windows", "multi-document generation"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["cross_encoder", "cohere", "hybrid", "semantic"],
        example_config={},
        decision_factors=[
            "Are you passing retrieved context to an LLM?",
            "Are you using more than 2 context chunks?",
        ],
        tradeoffs="Completely free accuracy boost based on LLM attention research. Virtually no downsides, should be the last step in any reranking pipeline.",
        pro_tip="Always use this as the final reranking step, after all other rerankers. It does not change what is retrieved, only the order for the LLM.",
    ),
    StrategyInfo(
        id="diversity",
        name="Diversity Reranking (MMR-based)",
        category="reranking",
        summary="Reranks results using Maximal Marginal Relevance to balance relevance with diversity, reducing redundancy.",
        when_to_use=[
            "Top results are too similar to each other",
            "The answer benefits from diverse perspectives",
            "Working with corpora that have many near-duplicate passages",
        ],
        when_not_to_use=[
            "You want the absolute most relevant results regardless of overlap",
            "Results are already diverse",
        ],
        best_for=["diverse answer generation", "summarization", "redundant corpora"],
        complexity="moderate",
        latency="moderate",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "recursive", "cross_encoder"],
        example_config={"lambda_param": 0.7, "top_n": 5},
        decision_factors=[
            "Are retrieved results too redundant?",
            "Does the answer need information from multiple angles?",
            "Is the corpus known to have near-duplicates?",
        ],
        tradeoffs="Effectively reduces redundancy in final results, but requires embedding computation for diversity scoring and may deprioritize the single most relevant chunk.",
        pro_tip="Use lambda_param=0.7 as default. Lower values (0.5) maximize diversity, higher values (0.9) favor relevance.",
    ),
    StrategyInfo(
        id="listwise_llm",
        name="Listwise LLM Reranking (RankGPT-style)",
        category="reranking",
        summary="Passes the entire candidate list to an LLM for holistic ranking using sliding window approach.",
        when_to_use=[
            "Maximum reranking quality is needed",
            "Budget allows an LLM call for reranking",
            "Candidate set is moderate (5-20 documents)",
        ],
        when_not_to_use=[
            "Latency is critical",
            "Budget is tight",
            "Candidate set is very large",
        ],
        best_for=["high-stakes search", "premium user experiences", "evaluation benchmarks"],
        complexity="advanced",
        latency="slow",
        cost="high",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="state-of-art",
        pairs_well_with=["hybrid", "recursive", "lost_in_middle"],
        example_config={"llm_model": "gpt-4o", "window_size": 10, "step_size": 5},
        decision_factors=[
            "Is this the highest-stakes ranking task?",
            "Can you afford the LLM cost and latency?",
            "Is the candidate set reasonable (5-20 items)?",
        ],
        tradeoffs="Highest possible reranking quality using full LLM reasoning, but the most expensive and slowest option.",
        pro_tip="Use a sliding window (window_size=10, step_size=5) to handle more than 10 candidates. Always pre-filter with a fast reranker first.",
    ),
    StrategyInfo(
        id="pairwise_llm",
        name="Pairwise LLM Reranking",
        category="reranking",
        summary="Uses an LLM to compare document pairs in a tournament-style bracket to determine the best ranking.",
        when_to_use=[
            "You need very precise ranking of a small set",
            "Listwise ranking is too expensive",
            "You want explainable pairwise comparisons",
        ],
        when_not_to_use=[
            "Candidate set is large (O(n^2) comparisons)",
            "Latency is critical",
            "Budget is constrained",
        ],
        best_for=["small candidate sets (3-8)", "high-precision ranking", "evaluation"],
        complexity="advanced",
        latency="slow",
        cost="high",
        requires_llm=True,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "recursive", "lost_in_middle"],
        example_config={"llm_model": "gpt-4o-mini", "top_n": 3},
        decision_factors=[
            "Is the candidate set very small (3-8 items)?",
            "Do you need detailed comparison reasoning?",
            "Can you afford O(n^2) LLM calls?",
        ],
        tradeoffs="Very precise ranking through direct comparisons, but O(n^2) LLM calls make it impractical for more than about 8 candidates.",
        pro_tip="Use a tournament bracket approach rather than all-pairs comparison to reduce LLM calls from O(n^2) to O(n log n).",
    ),
    StrategyInfo(
        id="flashrank",
        name="FlashRank Reranking",
        category="reranking",
        summary="Ultra-lightweight, CPU-only reranking model optimized for speed and minimal resource usage.",
        when_to_use=[
            "Running on CPU-only infrastructure",
            "Resource constraints are tight (memory, compute)",
            "You need the fastest possible neural reranking",
        ],
        when_not_to_use=[
            "Maximum accuracy is more important than speed",
            "You have GPU resources available",
        ],
        best_for=["resource-constrained environments", "edge deployment", "high-throughput systems"],
        complexity="simple",
        latency="fast",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["hybrid", "recursive", "lost_in_middle"],
        example_config={"model_name": "ms-marco-TinyBERT-L-2-v2", "top_n": 5},
        decision_factors=[
            "Is the deployment environment resource-constrained?",
            "Is speed more important than maximum accuracy?",
            "Do you need a free, self-hosted reranker?",
        ],
        tradeoffs="Extremely fast and lightweight with surprisingly good accuracy for its size, but cannot match larger cross-encoder models on hard queries.",
        pro_tip="Use as the first stage in a cascade pipeline: FlashRank filters the top 20 to 10, then a cross-encoder picks the top 5.",
    ),
    StrategyInfo(
        id="bge",
        name="BGE Reranker",
        category="reranking",
        summary="BAAI's open-source cross-encoder reranker, offering strong accuracy as a free alternative to commercial APIs.",
        when_to_use=[
            "You want a strong open-source reranker",
            "No budget for commercial reranking APIs",
            "Working with multilingual content",
        ],
        when_not_to_use=[
            "Model download size is a concern",
            "You need the absolute fastest reranking",
        ],
        best_for=["open-source pipelines", "multilingual reranking", "self-hosted systems"],
        complexity="moderate",
        latency="moderate",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "code_aware", "lost_in_middle"],
        example_config={"model_name": "BAAI/bge-reranker-base", "top_n": 5},
        decision_factors=[
            "Do you need a free, high-quality reranker?",
            "Is multilingual support needed?",
            "Can you host a ~1GB model?",
        ],
        tradeoffs="Strong open-source alternative to commercial rerankers with multilingual support, but requires model download and more memory than FlashRank.",
        pro_tip="Use bge-reranker-base for a good balance. Upgrade to bge-reranker-large only if the accuracy bump justifies the 2x memory cost.",
    ),
    StrategyInfo(
        id="contextual_rerank",
        name="Contextual Reranking",
        category="reranking",
        summary="Enriches chunks with metadata context before scoring, helping the reranker make better decisions.",
        when_to_use=[
            "Chunks have important metadata (source, date, section title)",
            "Metadata should influence ranking",
            "Working with multi-source corpora",
        ],
        when_not_to_use=[
            "Chunks have no meaningful metadata",
            "The base reranker already handles metadata",
        ],
        best_for=["metadata-rich corpora", "multi-source search", "enterprise documents"],
        complexity="moderate",
        latency="moderate",
        cost="free",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="good",
        pairs_well_with=["metadata_filter", "heading_based", "cross_encoder"],
        example_config={"base_reranker": "cross_encoder", "metadata_keys": ["source", "section", "date"]},
        decision_factors=[
            "Do chunks have metadata that should affect ranking?",
            "Does the source or section of a chunk matter for relevance?",
            "Do you want metadata-aware reranking without an LLM?",
        ],
        tradeoffs="Adds metadata awareness to any reranker for better context-sensitive scoring, but adds overhead of metadata injection and increases input length.",
        pro_tip="Include only the 2-3 most relevant metadata fields. Too much metadata dilutes the semantic signal.",
    ),
    StrategyInfo(
        id="cascade",
        name="Cascade Reranking",
        category="reranking",
        summary="Multi-stage reranking pipeline that uses fast, cheap rerankers to filter before expensive, precise ones.",
        when_to_use=[
            "You want production-grade reranking with cost control",
            "Candidate set is large and needs progressive filtering",
            "You want the best accuracy within a latency budget",
        ],
        when_not_to_use=[
            "Candidate set is already small (<10 items)",
            "Simplicity is preferred over optimization",
        ],
        best_for=["production pipelines", "large candidate sets", "cost-optimized reranking"],
        complexity="advanced",
        latency="moderate",
        cost="low",
        requires_llm=False,
        requires_gpu=False,
        accuracy_tier="excellent",
        pairs_well_with=["hybrid", "recursive", "ensemble"],
        example_config={
            "stages": [
                {"reranker": "flashrank", "top_n": 20},
                {"reranker": "cross_encoder", "top_n": 5},
            ]
        },
        decision_factors=[
            "Is the initial candidate set large (>20 items)?",
            "Do you want to balance cost and accuracy?",
            "Are you building a production system?",
        ],
        tradeoffs="Optimizes the cost/accuracy curve by using cheap fast models to filter before expensive precise models, but adds pipeline complexity.",
        pro_tip="A classic cascade: BM25 (100 -> 50) -> FlashRank (50 -> 15) -> Cross-Encoder (15 -> 5). Each stage narrows by roughly 3x.",
    ),
]


# ---------------------------------------------------------------------------
# StrategyGuide public API
# ---------------------------------------------------------------------------

class StrategyGuide:
    """Central registry and query interface for all strategy information."""

    def __init__(self) -> None:
        self._strategies: dict[str, StrategyInfo] = {}
        for s in _CHUNKING_STRATEGIES + _RETRIEVAL_STRATEGIES + _RERANKING_STRATEGIES:
            self._strategies[s.id] = s

    # -- queries --

    def all_strategies(self) -> list[StrategyInfo]:
        """Return every registered strategy."""
        return list(self._strategies.values())

    def get(self, strategy_id: str) -> StrategyInfo | None:
        """Look up a single strategy by ID."""
        return self._strategies.get(strategy_id)

    def by_category(self, category: str) -> list[StrategyInfo]:
        """Return all strategies in a given category."""
        return [s for s in self._strategies.values() if s.category == category]

    def get_pairs(self, strategy_id: str) -> list[StrategyInfo]:
        """Return strategies that pair well with the given one."""
        s = self._strategies.get(strategy_id)
        if s is None:
            return []
        return [
            self._strategies[pid]
            for pid in s.pairs_well_with
            if pid in self._strategies
        ]

    def compare(self, ids: list[str]) -> list[StrategyInfo]:
        """Return the full info for a list of strategy IDs (for side-by-side comparison)."""
        result = []
        for sid in ids:
            info = self._strategies.get(sid)
            if info is not None:
                result.append(info)
        return result


# Module-level singleton
strategy_guide = StrategyGuide()
