"""
Code templates for the generated RAG pipeline.

All generated code is framework-agnostic: no LangChain, no LlamaIndex.
Just clean Python with FastAPI, asyncpg, and direct API calls.
"""

# ---------------------------------------------------------------------------
# main.py -- FastAPI server
# ---------------------------------------------------------------------------
main_template = '''\
"""
RAG Pipeline Server
Generated by ChunkScope - https://github.com/chunkscope
Framework-agnostic: FastAPI + asyncpg + direct API calls.
"""
import os
from contextlib import asynccontextmanager

from dotenv import load_dotenv
from fastapi import FastAPI, File, HTTPException, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

from pipeline import embed_chunks, generate_answer, retrieve, rerank, chunk_text

load_dotenv()


# --------------- request / response models ---------------

class QueryRequest(BaseModel):
    question: str
    top_k: int = {top_k}


class QueryResponse(BaseModel):
    answer: str
    sources: list[dict]


# --------------- application lifespan ---------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """Startup / shutdown hooks."""
    # Import here so env vars are loaded first
    import asyncpg

    pool = await asyncpg.create_pool(dsn=os.getenv("DATABASE_URL"))
    app.state.pool = pool

    # Ensure the pgvector extension and chunks table exist
    async with pool.acquire() as conn:
        await conn.execute("CREATE EXTENSION IF NOT EXISTS vector;")
        await conn.execute("""
            CREATE TABLE IF NOT EXISTS chunks (
                id SERIAL PRIMARY KEY,
                content TEXT NOT NULL,
                embedding vector({embedding_dim}),
                metadata JSONB DEFAULT '{{}}'::jsonb
            );
        """)
    yield
    await pool.close()


app = FastAPI(
    title="RAG Pipeline",
    description="Generated by ChunkScope",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# --------------- endpoints ---------------

@app.get("/health")
async def health():
    return {{"status": "healthy"}}


@app.post("/query", response_model=QueryResponse)
async def query(req: QueryRequest):
    """Accept a question and return an answer with sources."""
    try:
        # Step 1 - Retrieve relevant chunks
        results = await retrieve(req.question, req.top_k, app.state.pool)

        # Step 2 - Rerank (if configured)
        results = rerank(req.question, results)

        # Step 3 - Generate answer using LLM
        context = "\\n\\n".join(r["content"] for r in results)
        answer = await generate_answer(req.question, context)

        return QueryResponse(answer=answer, sources=results)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))


@app.post("/ingest")
async def ingest(file: UploadFile = File(...)):
    """Upload a file, chunk it, embed it, and store in the vector database."""
    try:
        raw = await file.read()
        text = raw.decode("utf-8", errors="replace")

        # Step 1 - Chunk the text
        chunks = chunk_text(text)

        # Step 2 - Embed the chunks
        embeddings = await embed_chunks(chunks)

        # Step 3 - Store in pgvector
        async with app.state.pool.acquire() as conn:
            for chunk_text_item, emb in zip(chunks, embeddings):
                await conn.execute(
                    "INSERT INTO chunks (content, embedding, metadata) VALUES ($1, $2, $3)",
                    chunk_text_item,
                    str(emb),
                    '{{"source": "{{}}"}}'.format(file.filename),
                )

        return {{"status": "ok", "chunks_stored": len(chunks)}}
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc))
'''

# ---------------------------------------------------------------------------
# pipeline.py -- Core RAG logic
# ---------------------------------------------------------------------------
pipeline_template = '''\
"""
RAG Pipeline Logic
Generated by ChunkScope

Chunking   : {chunking_method} (size={chunk_size}, overlap={overlap})
Embedding  : {embedding_model}
Retrieval  : top-k cosine similarity
Reranker   : {reranker}
LLM        : {llm_model}
"""
import os
from typing import Any

import asyncpg
{extra_imports}
from chunker import chunk as _chunk


# ===== Chunking =====

def chunk_text(text: str) -> list[str]:
    """Split *text* into chunks using the configured strategy."""
    return _chunk(
        text,
        method="{chunking_method}",
        chunk_size={chunk_size},
        overlap={overlap},
    )


# ===== Embedding =====

async def embed_chunks(chunks: list[str]) -> list[list[float]]:
    """Embed a list of text chunks and return vectors."""
{embed_body}


# ===== Retrieval =====

async def retrieve(
    query: str,
    top_k: int,
    pool: asyncpg.Pool,
) -> list[dict[str, Any]]:
    """Retrieve the top-k most similar chunks from pgvector."""
    query_embedding = (await embed_chunks([query]))[0]

    async with pool.acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT id, content, metadata,
                   1 - (embedding <=> $1::vector) AS similarity
            FROM chunks
            ORDER BY embedding <=> $1::vector
            LIMIT $2
            """,
            str(query_embedding),
            top_k,
        )

    return [
        {{
            "id": row["id"],
            "content": row["content"],
            "similarity": float(row["similarity"]),
            "metadata": row["metadata"],
        }}
        for row in rows
    ]


# ===== Reranking =====

def rerank(query: str, results: list[dict]) -> list[dict]:
    """Optionally rerank retrieved results."""
{rerank_body}


# ===== Generation =====

async def generate_answer(query: str, context: str) -> str:
    """Use an LLM to generate an answer grounded in the retrieved context."""
{generate_body}
'''

# ---------------------------------------------------------------------------
# chunker.py -- Chunking implementations
# ---------------------------------------------------------------------------
chunker_template = '''\
"""
Text chunking utilities.
Generated by ChunkScope.

Supported methods: fixed, recursive, sentence, paragraph
"""
import re


def chunk(
    text: str,
    method: str = "fixed",
    chunk_size: int = 512,
    overlap: int = 50,
) -> list[str]:
    """
    Split *text* into chunks.

    Parameters
    ----------
    text : str
        The raw text to chunk.
    method : str
        One of "fixed", "recursive", "sentence", "paragraph".
    chunk_size : int
        Target chunk size in characters.
    overlap : int
        Number of overlapping characters between consecutive chunks.
    """
    dispatch = {{
        "fixed": _fixed_chunk,
        "recursive": _recursive_chunk,
        "sentence": _sentence_chunk,
        "paragraph": _paragraph_chunk,
    }}
    fn = dispatch.get(method)
    if fn is None:
        raise ValueError(f"Unknown chunking method: {{method}}")
    return fn(text, chunk_size, overlap)


# ----- Fixed-size chunking -----

def _fixed_chunk(text: str, size: int, overlap: int) -> list[str]:
    """Simple character-level sliding window."""
    chunks: list[str] = []
    start = 0
    while start < len(text):
        end = start + size
        chunks.append(text[start:end])
        start += size - overlap
    return chunks


# ----- Recursive chunking -----

_SEPARATORS = ["\\n\\n", "\\n", ". ", " ", ""]


def _recursive_chunk(text: str, size: int, overlap: int) -> list[str]:
    """Recursively split on decreasingly fine separators."""
    return _split_recursive(text, _SEPARATORS, size, overlap)


def _split_recursive(
    text: str, separators: list[str], size: int, overlap: int
) -> list[str]:
    if len(text) <= size:
        return [text] if text.strip() else []

    sep = separators[0] if separators else ""
    if sep == "":
        return _fixed_chunk(text, size, overlap)

    parts = text.split(sep)
    chunks: list[str] = []
    current = ""
    for part in parts:
        candidate = current + sep + part if current else part
        if len(candidate) > size and current:
            chunks.append(current)
            # Keep overlap from the end of the previous chunk
            current = current[-overlap:] + sep + part if overlap else part
        else:
            current = candidate
    if current.strip():
        chunks.append(current)

    # If any chunk is still too large, split it with the next separator
    if len(separators) > 1:
        refined: list[str] = []
        for c in chunks:
            if len(c) > size:
                refined.extend(_split_recursive(c, separators[1:], size, overlap))
            else:
                refined.append(c)
        return refined
    return chunks


# ----- Sentence-based chunking -----

_SENTENCE_RE = re.compile(r"(?<=[.!?])\\s+")


def _sentence_chunk(text: str, size: int, overlap: int) -> list[str]:
    """Group sentences into chunks up to *size* characters."""
    sentences = _SENTENCE_RE.split(text)
    chunks: list[str] = []
    current = ""
    for sent in sentences:
        if len(current) + len(sent) + 1 > size and current:
            chunks.append(current.strip())
            # Overlap: keep the last *overlap* characters of the previous chunk
            current = current[-overlap:] + " " + sent if overlap else sent
        else:
            current = current + " " + sent if current else sent
    if current.strip():
        chunks.append(current.strip())
    return chunks


# ----- Paragraph chunking -----

def _paragraph_chunk(text: str, size: int, overlap: int) -> list[str]:
    """Split on double-newlines (paragraphs), merging short ones."""
    paragraphs = [p.strip() for p in text.split("\\n\\n") if p.strip()]
    chunks: list[str] = []
    current = ""
    for para in paragraphs:
        if len(current) + len(para) + 2 > size and current:
            chunks.append(current)
            current = current[-overlap:] + "\\n\\n" + para if overlap else para
        else:
            current = current + "\\n\\n" + para if current else para
    if current.strip():
        chunks.append(current)
    return chunks
'''

# ---------------------------------------------------------------------------
# requirements.txt
# ---------------------------------------------------------------------------
requirements_template = '''\
# Core
fastapi==0.115.*
uvicorn[standard]==0.34.*
asyncpg==0.30.*
python-dotenv==1.1.*
pydantic==2.*
python-multipart==0.0.*
{extra_requirements}
'''

# ---------------------------------------------------------------------------
# Dockerfile
# ---------------------------------------------------------------------------
dockerfile_template = '''\
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    build-essential \\
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
'''

# ---------------------------------------------------------------------------
# docker-compose.yml
# ---------------------------------------------------------------------------
docker_compose_template = '''\
version: "3.9"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: ${{POSTGRES_USER:-rag}}
      POSTGRES_PASSWORD: ${{POSTGRES_PASSWORD:-rag_secret}}
      POSTGRES_DB: ${{POSTGRES_DB:-ragdb}}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rag"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
'''

# ---------------------------------------------------------------------------
# .env.example
# ---------------------------------------------------------------------------
env_template = '''\
# Database
DATABASE_URL=postgresql://rag:rag_secret@db:5432/ragdb
POSTGRES_USER=rag
POSTGRES_PASSWORD=rag_secret
POSTGRES_DB=ragdb

# Embedding provider
{env_embedding_vars}

# LLM provider
{env_llm_vars}
'''

# ---------------------------------------------------------------------------
# README.md
# ---------------------------------------------------------------------------
readme_template = '''\
# RAG Pipeline

> Auto-generated by **ChunkScope**.

## Configuration

| Setting | Value |
|---------|-------|
| Chunking | {chunking_method} (size={chunk_size}, overlap={overlap}) |
| Embedding | {embedding_model} |
| Retrieval | top-k={top_k} |
| Reranker | {reranker} |
| LLM | {llm_model} |

## Quick Start

1. Copy `.env.example` to `.env` and fill in your API keys.
2. Run:

```bash
docker compose up --build
```

3. Open [http://localhost:8000/docs](http://localhost:8000/docs) to explore the API.

## Endpoints

| Method | Path | Description |
|--------|------|-------------|
| GET | `/health` | Health check |
| POST | `/ingest` | Upload a file to chunk, embed, and store |
| POST | `/query` | Ask a question and get an answer with sources |

## Project Structure

```
.
├── main.py            # FastAPI application
├── pipeline.py        # RAG pipeline (embed, retrieve, rerank, generate)
├── chunker.py         # Text chunking implementations
├── requirements.txt
├── Dockerfile
├── docker-compose.yml
├── .env.example
└── README.md
```

## How It Works

1. **Ingest** -- Upload a document. The server chunks the text using the
   *{chunking_method}* strategy, embeds each chunk with *{embedding_model}*,
   and stores the vectors in PostgreSQL + pgvector.
2. **Query** -- Send a question. The server embeds the query, retrieves the
   most similar chunks, optionally reranks them, and passes the context to
   *{llm_model}* to produce a grounded answer.
'''
